### PR TITLE
Introduce Dockerfile

### PR DESCRIPTION
**Pull request by themarcelor**
Introducing a Dockerfile to help others with a quick method to execute CIEL, so anyone can get up to speed with it without having to spend time with any local configuration.

Testing results:
```
% docker run -it ciel-docker /bin/bash
root@0ee2dd9214d9:/home# ciel --version
ciel version 0.1
```

### CODE REVIEW

**Comment by vindarel** [comment]
Awe-some, thanks a lot :pray: 

I'll try ASAP, it looks simple and perfect though. 

ps:  I'm trying to get some time away from keyboard in August, I don't promise on being super reactive!

**Comment by vindarel** [comment]
We can simplify the Dockerfile a bit, the image has a built-in way to get Quicklisp:

```
before_script:
  - QUICKLISP_ADD_TO_INIT_FILE=true /usr/local/bin/install-quicklisp
```

**Comment by themarcelor** [comment]
Great catch @vindarel 😃 I've pushed a new commit. Please take another look when you have a chance. 😎

**Comment by themarcelor** [comment]
Nice! 👍🏼 @vindarel Let me know you think we should add some note to the `README.md` about this.

**Comment by themarcelor** [comment]
@vindarel yeah, that `make image` command works fine inside the container 🎉 

```
CIEL [master] % docker run -it ciel /bin/bash
root@5522fd70b9a0:/home# make image
sbcl --load build-image.lisp
...
  Load 1 ASDF system:
    ciel
; Loading "ciel"
..................................................
[package osicat]..................................
[package moira]..........
[undoing binding stack and other enclosing state... done]
[performing final GC... done]
[saving current Lisp image into ciel-core:
writing 1840 bytes from the read-only space at 0xf0000000
writing 3056 bytes from the static space at 0xf0200000
writing 130220032 bytes from the dynamic space at 0x1000000000
done]
root@5522fd70b9a0:/home# echo $?
0
```

Regarding the `COPY . .`, I agree that we don't need / shouldn't copy everything.
Perhaps we should limit the list to:

- `COPY Makefile .`
- `COPY src .`
- `COPY build-image.lisp  ciel.asd  find-dependencies.lisp  repl.lisp shell-utils.lisp utils.lisp  build-config.lisp repl-utils.lisp scripting.lisp .`

?

btw, the `apt-cache` is an amazing idea 💡 I can cut a new PR later this week.

**Pull request merged**
